/// Minimal currency name map (ISO-4217 code -> display name).
///
/// ExchangeRate-API `latest/{base}` returns codes + rates but not names.
/// We keep a small friendly map for common currencies and fall back to code.
const Map<String, String> kCurrencyNames = {
  'USD': 'US Dollar',
  'EUR': 'Euro',
  'GBP': 'British Pound',
  'JPY': 'Japanese Yen',
  'AUD': 'Australian Dollar',
  'CAD': 'Canadian Dollar',
  'CHF': 'Swiss Franc',
  'CNY': 'Chinese Yuan',
  'HKD': 'Hong Kong Dollar',
  'SGD': 'Singapore Dollar',
  'INR': 'Indian Rupee',
  'KRW': 'South Korean Won',
  'SEK': 'Swedish Krona',
  'NOK': 'Norwegian Krone',
  'DKK': 'Danish Krone',
  'NZD': 'New Zealand Dollar',
  'MXN': 'Mexican Peso',
  'BRL': 'Brazilian Real',
  'ZAR': 'South African Rand',
  'TRY': 'Turkish Lira',
  'RUB': 'Russian Ruble',
  'PLN': 'Polish Złoty',
  'CZK': 'Czech Koruna',
  'HUF': 'Hungarian Forint',
  'ILS': 'Israeli New Shekel',
  'SAR': 'Saudi Riyal',
  'AED': 'UAE Dirham',
  'QAR': 'Qatari Riyal',
  'KWD': 'Kuwaiti Dinar',
  'EGP': 'Egyptian Pound',
  'NGN': 'Nigerian Naira',
  'PKR': 'Pakistani Rupee',
  'BDT': 'Bangladeshi Taka',
  'IDR': 'Indonesian Rupiah',
  'MYR': 'Malaysian Ringgit',
  'THB': 'Thai Baht',
  'VND': 'Vietnamese Dong',
  'PHP': 'Philippine Peso',
  'TWD': 'New Taiwan Dollar',
  'UAH': 'Ukrainian Hryvnia',
  'RON': 'Romanian Leu',
  'BGN': 'Bulgarian Lev',
  'KES': 'Kenyan Shilling',
  'UGX': 'Ugandan Shilling',
  'TZS': 'Tanzanian Shilling',
  'RWF': 'Rwandan Franc',
  'GHS': 'Ghanaian Cedi',
  'ETB': 'Ethiopian Birr',
  'LKR': 'Sri Lankan Rupee',
  'MUR': 'Mauritian Rupee',
  'MNT': 'Mongolian Tögrög',
  'MMK': 'Myanmar Kyat',
  'LAK': 'Lao Kip',
  'KHR': 'Cambodian Riel',
};


